// import { Link } from "react-router-dom";

import Header from "../Components/_Header";
import FooterTop from "../Components/_FooterTop";
import Contact from "../Components/_Contact";
import Footer from "../Components/_Footer";

const ThirdPartyTermsOfUse = () => {
  return (
    <>
      <Header />

      <section className="Documentation-content">
        <div className="container">
          <div className="d-flex flex-column gap-2">
            <h2>Third Party Terms Of Use</h2>
          </div>
        </div>
        <div className="container mt-5">
          <div className="points">
            <article>
              <h5>Express disclaimers for Predictive Third Party Content</h5>
              <p>
                However, the predictive content is not being generated by
                www.Nobleshaadi.com in-house but has been outsourced to another
                entity and such outsourced content is being delivered through
                the channel of www.Nobleshaadi.com.
              </p>
              <p>
                An astrological prediction is just an opinion of the astrologer
                and has no scientific authenticity. These predictions are based
                upon the characteristics, placements, aspects, associations,
                strengths, weaknesses of the planets and the ability, grip over
                the subject and experience of the astrologer in Vedic astrology.
              </p>
              <p>
                A Vedic astrological horoscope is the opinion of one person
                based on his or her training and experience in the subject. On
                receiving a particular enquiry from a client, this query is
                passed to a panel of astrologers for the predictions/remedies
                and answered within 7 working days or earlier. Generally 2-3
                astrologers give their predictions for an enquiry. Another
                astrologer's opinion on any particular point might differ.
                Recommendation for astrological remedies such as gemstones,
                mantras, yantras etc. are often prescribed by astrologers, after
                a diligent study of the client's birth chart and with due
                exercise of his prudence and judgment. All Predictions are made
                based on Horoscope prepared on Birth Database provided by the
                Client in accordance to the principals of Vedic Astrology.
              </p>
              <p>
                Though all the predictions are provided by a panel of eminent
                astrologers, the same should not be used as a substitute to an
                advice of a licensed professional, medical / psychiatric
                treatment, study, a curriculum, profession or life style or
                treatment that you would normally receive from a licensed
                professional, such as a lawyer, doctor, psychiatrist, or
                financial advisor. The predictions, opinions and remedial
                measures of two astrologers on one horoscope may differ and have
                varied results. It must be clearly understood that every such
                prescription is accompanied by a prescribed method and
                procedure, which is expected to be followed by our clients with
                due diligence. Broxham Universal Limited is not responsible for
                any claims for negative functioning of any prescription of
                astrological remedy made by any of astrologers working for
                matchstro.com.
              </p>
              <h5>DISCLAIMER</h5>
              <p>
                Broxham Universal Limited does not itself engage in astrological
                predictions and has instead, outsourced the work of astrological
                predictions to an expert third party content provider. As such,
                Broxham Universal Limited cannot be held responsible in any way
                for the inaccuracy of any prediction. Broxham Universal Limited
                makes no warranties or representations regarding the accuracy or
                significance of any aspect of the astrological horoscope, and
                cannot be responsible for any interpretation or use that may be
                made of it. Readings may differ from astrologer to astrologer.
              </p>
              <p>
                Further, the management of Broxham Universal Limited does not
                guarantee the accuracy of predictions and disclaim any
                responsibility for any decision(s) or its consequences taken by
                any person based on predictions made on the information
                available from the client.
              </p>
              <p>
                The web site www.Nobleshaadi.com makes no warranty or
                representation regarding the web site, any content or products
                provided in connection with the web site, including paid
                astrological services and consultations. We expressly disclaim
                any and all warranties, express or implied, including any
                warranty as to the availability, accuracy, completeness or
                content of information, products or services including
                astrological prediction services, which are part of
                www.Nobleshaadi.com.
              </p>
              <p>
                Broxham Universal Limited also disclaims any or all warranties
                or fitness for a particular purpose, merchantability or against
                infringement. In no event will Broxham Universal Limited or its
                employees, be liable for any damages or losses, including
                without, limitation, indirect, consequential, special,
                incidental or punitive damages resulting from or caused by the
                Broxham Universal Limited's web site, its contents or any errors
                or omissions in its contents, even if advised of the
                possibilities of such damages.
              </p>
              <h5>LIMITATION OF LIABILITY</h5>
              <p>
                Under no circumstances and under no legal theory, tort,
                contract, or otherwise, shall Broxham Universal Limited or its
                management be liable to the user or any other person for any
                indirect, special, incidental, or consequential damages of any
                character including, without limitation, damages resulting from
                the use of or the inability to use the www.jeevansathi.com
                service, including its predictive and /or other astrological
                services, or damages for loss of goodwill, business profit,
                business stoppage, loss of data or business information,
                computer damage, or damages resulting from unauthorized access
                to or changes made to user's transmissions or data, or any and
                all other commercial damages or losses. It is understood that
                the materials provided are for your personal information only
                and do not construe to be any specific advice to you.
              </p>
              <p>
                We shall not be held responsible for personal or business losses
                arising from using or not using our services in any way. Please
                use your own discretion when following our advice including
                astrological prediction services.
              </p>
              <p>
                Any action taken by the user on the basis of the information ,
                astrological or otherwise, contained in this site is the user's
                responsibility alone and Broxham Universal Limited will not be
                liable in any manner for the consequences of such action taken
                by the user.
              </p>
              <p>
                The relationship between the user and www.nobleshaadi.com shall
                be governed by the laws of the Republic of India without regard
                to its conflict of law provisions.
              </p>
              <p>
                This site is the property of Broxham Universal Limited and is
                subject to Indian laws. www.Nobleshaadi.com reserves the right
                to make modifications and alterations in the material contained
                at this site without any prior notice of such modifications or
                alterations whatsoever.
              </p>
            </article>
          </div>
        </div>
      </section>

      <FooterTop />
      <Contact />
      <Footer />
    </>
  );
};

export default ThirdPartyTermsOfUse;
