import { createContext, useContext, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import hero1Jpg from "../Assets/images/hero1.jpg";
import hero2Jpg from "../Assets/images/hero2.jpg";
import hero3Jpg from "../Assets/images/hero3.jpg";

const StoreContext = createContext();

export function useStore() {
  return useContext(StoreContext);
}

export function StateStore({ children }) {
  const [login, setLogin] = useState(false);
  const [loading, setLoading] = useState(true);

  const navigate = useNavigate();
  const searchParams = (key) => {
    return new URL(window.location.href).searchParams.get(key);
  };

  const matrimonyType = {
    agra: {
      name: "Agra",
      // name: "NRI",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    bareilly: {
      name: "Bareilly",
      // name: "Assamese",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    chennai: {
      name: "Chennai",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    hydrabad: {
      name: "Hydrabad",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    mumbai: {
      name: "Mumbai",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    bangalore: {
      name: "Bangalore",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    delhi: {
      name: "Delhi",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    gurgaon: {
      name: "Gurgaon",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    goa: {
      name: "Goa",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    kolkata: {
      name: "Kolkata",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    mumbai: {
      name: "Mumbai",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    noida: {
      name: "Noida",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    pune: {
      name: "Pune",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    ghaziabad: {
      name: "Ghaziabad",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    noida: {
      name: "Noida",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    // haridwar: {
    //   name: "Haridwar",
    //   banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    // },
    shirdi: {
      name: "All",
      // name: "Shirdi",
      banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    },
    // varansi: {
    //   name: "Varansi",
    //   banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    // },
    // divorcee: {
    //   name: "All",
    //   banners: [hero1Jpg, hero2Jpg, hero3Jpg],
    // },
  };

  const data = {
    language: [
      "Bihari",
      "Bengali",
      "Hindi",
      "Gujrati",
      "Kannada",
      "Malayalam",
      "Marathi",
      "Oriya",
      "Punjabi",
      "Rajasthani",
      "Konkani",
      "Himachali",
      "Haryanvi",
      "Assamese",
      "Kashmiri",
      "Nepali",
      "Tulu",
    ],
    caste: [
      "Aggarwal",
      "Brahmin",
      "Khatri",
      "Rajput",
      "Arora",
      "Bania",
      "Sikh Jat",
      "Vaishnav",
      "Aggarwal",
      "Brahmin",
      "Khatri",
      "Rajput",
      "Arora",
      "Bania",
      "Sikh Jat",
      "Vaishnav",
      "Aggarwal",
      "Brahmin",
      "Khatri",
      "Rajput",
      "Arora",
      "Bania",
      "Sikh Jat",
    ],
    religion: [
      "Hindu",
      "Muslim",
      "Christian",
      "Buddhist",
      "Sikh",
      "Jain",
      "Parsi",
      "Jewish",
      "Bahai",
    ],
    city: [
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
    ],
    state: [
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
      "Panvel",
      "Kolkata",
      "Pune",
      "Lucknow",
      "New Delhi",
    ],
    nri: [
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
      "United States",
    ],
    age: [
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "41",
      "42",
      "43",
      "44",
      "45",
      "46",
      "47",
      "48",
      "49",
      "50",
      "51",
      "52",
      "53",
      "54",
      "55",
      "56",
      "57",
      "58",
      "59",
      "60",
      "61",
      "62",
      "63",
      "64",
      "65",
      "66",
      "67",
      "68",
      "69",
      "70",
    ],
    height: [
      "4.0 Ft",
      "4.1 Ft",
      "4.2 Ft",
      "4.3 Ft",
      "4.4 Ft",
      "4.5 Ft",
      "4.6 Ft",
      "4.7 Ft",
      "4.8 Ft",
      "4.9 Ft",
      "4.10 Ft",
      "4.11 Ft",
      "5.0 Ft",
      "5.1 Ft",
      "5.2 Ft",
      "5.3 Ft",
      "5.4 Ft",
      "5.5 Ft",
      "5.6 Ft",
      "5.7 Ft",
      "5.8 Ft",
      "5.9 Ft",
      "5.10 Ft",
      "5.11 Ft",
      "6.0 Ft",
      "6.1 Ft",
      "6.2 Ft",
      "6.3 Ft",
      "6.4 Ft",
      "6.5 Ft",
      "6.6 Ft",
      "6.7 Ft",
      "6.8 Ft",
      "6.9 Ft",
      "6.10 Ft",
      "6.11 Ft",
      "7.0 Ft",
    ],
    maritalStatus: [
      "Never Married",
      "Awating Divorce",
      "Divorced",
      "Widowed",
      "Annulled",
    ],
    haveChildren: ["No", "Yes, Living Together", "Yes, Living Separately"],
    country: [
      "India",
      "Australia",
      "Dubai",
      "London",
      "Italy",
      "Rome",
      "Russia",
    ],
    manglik: ["Manglik", "Non Manglik", "Angshik Manglik"],
    highestEducation: [
      "B.Arch",
      "B.Des",
      "B.E / B.Tech",
      "B.Pharma",
      "M.Arch",
      "M.Des",
      "M.E / M.Tech",
      "M.Pharma",
      "M.S ( Engineering )",
    ],
    occupation: [
      "Government",
      "Civil Services",
      "Defence",
      "Self Employed",
      "Not Working",
      "Doctor",
      "Engineering",
      "Architect",
    ],
    income: {
      rupee: [
        "No Income",
        "Rs. 1 Lakh",
        "Rs. 2 Lakh",
        "Rs. 3 Lakh",
        "Rs. 4 Lakh",
        "Rs. 5 Lakh",
        "Rs. 7.5 Lakh",
        "Rs. 10 Lakh",
        "Rs. 15 Lakh",
        "Rs. 20 Lakh",
        "Rs. 25 Lakh",
        "Rs. 35 Lakh",
        "Rs. 50 Lakh",
        "Rs. 70 Lakh",
        "Rs. 1 Crore",
        "And Above",
      ],
      dollar: [
        "No Income",
        "25,000 USD",
        "40,000 USD",
        "60,000 USD",
        "80,000 USD",
        "100,000 USD",
        "150,000 USD",
        "200,000 USD",
        "And Above",
      ],
    },
    dietaryHabits: ["Vegetarian", "Non Vegetarian", "Jain", "Eggetarian"],
    drinkingHabits: ["Yes", "No", "Occasionally"],
    smokingHabits: ["Yes", "No", "Occasionally"],
    challenged: [
      "Doesn't Matter",
      "None",
      "Cripple",
      "Hearing Impaired",
      "Visually Impaired",
      "Others",
    ],
  };

  const membershipData = {
    membershipPlans: {
      ePrime: {
        packages: [
          {
            duration: "3 Months",
            price: "4900",
            offerPrice: "1999",
            contactAccess: 0,
          },
          {
            duration: "6 Months",
            price: "5600",
            offerPrice: "2699",
            contactAccess: 0,
          },
          {
            duration: "12 Months",
            price: "8400",
            offerPrice: "4999",
            contactAccess: 0,
          },
        ],
        benefits: 2,
      },
      eGold: {
        packages: [
          {
            duration: "3 Months",
            price: "6900",
            offerPrice: "2999",
            contactAccess: 60,
          },
          {
            duration: "6 Months",
            price: "9999",
            offerPrice: "4999",
            contactAccess: 130,
          },
          {
            duration: "12 Months",
            price: "12500",
            offerPrice: "6999",
            contactAccess: 250,
          },
        ],
        benefits: 4,
      },
      eDiamond: {
        packages: [
          {
            duration: "3 Months",
            price: "12999",
            offerPrice: "5999",
            contactAccess: 100,
          },
          {
            duration: "6 Months",
            price: "16999",
            offerPrice: "9890",
            contactAccess: 220,
          },
          {
            duration: "12 Months",
            price: "18999",
            offerPrice: "12999",
            contactAccess: 480,
          },
        ],
        benefits: 8,
      },
    },
    membershipBenefits: [
      "Send unlimited messages",
      "Priority customer service",
      "View contact numbers",
      "Unlimited voice & video calls",
      "Make your contact details visible",
      "On-top of search & daily recommendations",
      "Get match of the day notifications",
      "Online shaadi meet through video conferencing",
    ],
    nsPrivilegePlans: {
      packages: [
        {
          duration: "3 Months",
          price: "31000",
          offerPrice: "16999",
          benefits: [
            "Send unlimited messages to ePrime, eGold, eDiamond and Sapphire premier members.",
            "Contact profiles shortlisted by you and arrange meeting through video conferencing.",
            "Send interest to handpicked profiles matching your criteria.",
            "View contact details of 150 ePrime, eGold, eDiamond members.",
            "Unlimited Voice and Video Call.",
          ],
        },
        {
          duration: "6 Months",
          price: "52000",
          offerPrice: "31000",
          benefits: [
            "A relationship manager is assigned to you who will,",
            "Understand qualities that you are looking for in your desired partner.",
            "Send interest to hand picked profiles matching your criteria.",
            "Contact profiles shortlisted by you and arrange meeting through video conferencing.",
            "Send unlimited messages to ePrime, eGold, eDiamond and Sapphire premier members.",
            "Arrange meeting over video conferencing.",
            "Unlimited video and voice calls.",
            "View contact details of 200 no. of ePrime, eGold, eDiamond and 20 contacts of Sapphire premier members.",
          ],
        },
        {
          duration: "12 Months",
          price: "71000",
          offerPrice: "42000",
          benefits: [
            "A relationship manager is assigned to you who will,",
            "Understand qualities that you are looking for in your desired partner.",
            "Send interest to hand picked profiles matching your criteria.",
            "Contact profiles shortlisted by you and arrange meeting through video conferencing.",
            "Send unlimited messages to ePrime, eGold, eDiamond and Sapphire premier members.",
            "Arrange meeting over video conferencing.",
            "Unlimited video and voice calls.",
            "View contact details of 300 no. of ePrime, eGold, eDiamond and 40 contacts of Sapphire premier members.",
          ],
        },
      ],
    },
    sapphirePremierPlans: {
      packages: [
        {
          duration: "3 Months",
          price: "92000",
          offerPrice: "62000",
          benefits: [
            "A Relationship Manager is assigned to you who",
            "Send unlimited messages and chat with NS privilege and Sapphire Premier Members.",
            "Unlimited voice and video calls.",
            "View contact details of NS privilege and Sapphire Premier.",
            "Contact profiles shortlisted by you and arrange meeting throgh video conferencing.",
            "Sends interests to handpicked profiles matching your criteria to NS Privilege and Sapphire Premier.",
          ],
        },
        {
          duration: "6 Months",
          price: "120000",
          offerPrice: "92000",
          benefits: [
            "Understands qualities that you are looking for in your desired partner.",
            "Social media verification of all the selected profiles.",
            "Screening your profile with affluent HNIs profiles and arrange meeting with each other.",
            "Dedicated manager will share matched profiles on weekly basis.",
            "Sends interests to handpicked profiles matching your criteria to NS Privilege and Sapphire Members.",
            "Send unlimited messages, chats, voice and video calls to NS Privilege & Sapphire Premier Members.",
            "View contact details of NS Privilege and Sapphire Premier Members.",
          ],
        },
        {
          duration: "12 Months",
          price: "200000",
          offerPrice: "142000",
          benefits: [
            "Understands qualities that you are looking for in your desired partner.",
            "Social media verification of all the selected profiles.",
            "Screening your profile with affluent HNIs profiles and arrange meeting with each other.",
            "Dedicated manager will share matched profiles on weekly basis.",
            "Sends interests to handpicked profiles matching your criteria to NS Privilege and Sapphire Members.",
            "Send unlimited messages, chats, voice and video calls to NS Privilege & Sapphire Premier Members.",
            "View contact details of NS Privilege and Sapphire Premier Members.",
          ],
        },
      ],
    },
  };

  useEffect(() => {
    setLoading(false);
  }, []);

  const value = {
    login,
    setLogin,
    data,
    matrimonyType,
    membershipData,
    navigate,
    searchParams,
  };

  return (
    <StoreContext.Provider value={value}>
      {!loading && children}
    </StoreContext.Provider>
  );
}
